import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Header from 'src/components/Header';

const Home: NextPage = () => {
    const [showPreloader, setShowPreloader] = useState(true);

    useEffect(() => {
        window.addEventListener('load', () => {
            setShowPreloader(false);
        });
    }, []);

    console.log({ showPreloader });
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header />
            </main>
            <footer></footer>
        </>
    );
};

export default Home;
